### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### User Create
POST localhost:8080/signup
Content-Type: application/json

{
  "username": "number3"
}

### Post Create
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "안녕 존나 졸립다",
  "content": "내용임",
  "user": {
    "id": 1,
    "username": "tjfwltn"
  }
}

### 한 게시글 조회
GET localhost:8080/posts/1

### 페이지 조회
GET localhost:8080/posts/lists/1

### Post Delete
DELETE localhost:8080/posts/1

### Post Update
PATCH localhost:8080/posts/1
Content-Type: application/json

{
  "title": "수정 시작222"
}

### 추천
POST localhost:8080/recommend/1
Content-Type: application/json

{
  "userId": 1
}

### 댓글작성
POST localhost:8080/posts/1/comments
Content-Type: application/json

{
  "userId": 1,
  "parentId": 7,
  "text": "대댓글확인"
}

### 대댓글작성
POST localhost:8080/posts/1/comments
Content-Type: application/json

{
  "userId": 2,
  "parentId": 1,
  "text": "취업하자"
}