### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### User Create
POST localhost:8080/signup
Content-Type: application/json

{
  "username": "test5"
}

### Post Create
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "안녕 존나 졸립다2",
  "content": "내용임2",
  "user": {
    "id": 2,
    "username": "test2"
  }
}

### 한 게시글 조회
GET localhost:8080/posts/2

### 페이지 조회
GET localhost:8080/posts/lists?page=

### Post Delete
DELETE localhost:8080/posts/1

### Post Update
PATCH localhost:8080/posts/1
Content-Type: application/json

{
  "title": "수정 시작222"
}

### 추천
POST localhost:8080/recommend/1
Content-Type: application/json

{
  "userId": 1
}

### 댓글작성
POST localhost:8080/posts/2/comments
Content-Type: application/json

{
  "userId": 4,
  "parentId": 1,
  "text": "첫번째 댓글에 대한 네번째 댓글"
}

### 대댓글작성
POST localhost:8080/posts/1/comments
Content-Type: application/json

{
  "userId": 2,
  "parentId": 1,
  "text": "취업하자"
}

### 댓글 정렬 기본순
GET localhost:8080/posts/2/comments

#### 댓글 정렬 최신순
#GET localhost:8080/posts/2/comments?sort=latest
#
#### 댓글 정렬 답글순
#GET localhost:8080/posts/2/comments?sort=replies